"""Tests for provenance.py — footer stamping and the delegated-pass table."""

import json

import pytest

import provenance


# --- helpers ---------------------------------------------------------------

SKILL_ROOT = "/Users/x/.claude/skills/jetredline"

# A prompt shaped like the ones SKILL.md builds for a delegated pass. The
# case-identifying text is deliberately distinctive so the leakage test can
# assert it never reaches the stamped report.
SECRET = "Roe-v-Doe-SEALED-FIXTURE"


def pass_prompt(stem, extra=SECRET):
    return (
        f"Read {SKILL_ROOT}/references/pass-instructions/{stem}.md and follow it. "
        f"The skill root is {SKILL_ROOT}. The draft is at /cases/{extra}.docx. "
        "Return only the structured entry list those instructions specify."
    )


def task_record(stem, model="claude-opus-4-8[1m]", **overrides):
    result = {
        "agentId": "agent_01",
        "agentType": "general-purpose",
        "content": [{"type": "text", "text": f"findings mentioning {SECRET}"}],
        "prompt": pass_prompt(stem),
        "resolvedModel": model,
        "status": "completed",
        "totalDurationMs": 201_000,
        "totalToolUseCount": 14,
        "totalTokens": 175_922,
        "usage": {
            "input_tokens": 2,
            "output_tokens": 11_807,
            "cache_creation_input_tokens": 11_323,
            "cache_read_input_tokens": 152_790,
        },
    }
    result.update(overrides)
    return {"type": "user", "toolUseResult": result}


def write_transcript(tmp_path, records, name="session.jsonl"):
    path = tmp_path / name
    with open(path, "w", encoding="utf-8") as fh:
        for r in records:
            fh.write(json.dumps(r) + "\n")
    return path


@pytest.fixture
def report(tmp_path):
    path = tmp_path / "OPINION-ANALYSIS.md"
    path.write_text("# Analysis\n\nSome findings.\n", encoding="utf-8")
    return path


def stamp_it(path, rows=None):
    provenance.stamp(path, "Claude Opus 5 (claude-opus-5)", "jetredline",
                     "4.13.0", "2026-08-07", rows)
    return path.read_text(encoding="utf-8")


# --- footer basics ---------------------------------------------------------

def test_stamp_appends_footer(report):
    text = stamp_it(report)
    assert "*Report generated by Claude Opus 5 (claude-opus-5) using jetredline v4.13.0 on 2026-08-07." in text
    assert text.count("Report generated by") == 1
    assert "# Analysis" in text


def test_stamp_is_idempotent_without_table(report):
    stamp_it(report)
    text = stamp_it(report)
    assert text.count("Report generated by") == 1
    assert text.count("---") == 1


def test_stamp_is_idempotent_with_table(report, tmp_path):
    rows = provenance.collect_subagent_rows(
        write_transcript(tmp_path, [task_record("pass2-style")])
    )
    stamp_it(report, rows)
    text = stamp_it(report, rows)
    assert text.count("Report generated by") == 1
    assert text.count("**Delegated passes**") == 1
    assert text.count("| 2 — Style |") == 1


def test_restamping_drops_a_stale_table(report, tmp_path):
    rows = provenance.collect_subagent_rows(
        write_transcript(tmp_path, [task_record("pass2-style")])
    )
    stamp_it(report, rows)
    text = stamp_it(report, [])          # e.g. re-run in a session with no passes
    assert "**Delegated passes**" not in text
    assert text.count("Report generated by") == 1


def test_quoted_footer_sentence_midbody_survives(tmp_path):
    """The regex is end-anchored: a report that quotes a footer isn't truncated."""
    path = tmp_path / "R.md"
    path.write_text(
        "# Analysis\n\n"
        "The prior report ended: *Report generated by Claude Opus 4.8 "
        "(claude-opus-4-8) using jetredline v4.4.0 on 2026-06-05.*\n\n"
        "That footer is quoted, not ours.\n",
        encoding="utf-8",
    )
    text = stamp_it(path)
    assert "That footer is quoted, not ours." in text
    assert text.count("Report generated by") == 2


# --- transcript parsing ----------------------------------------------------

def test_collects_one_row_per_delegated_pass(tmp_path):
    transcript = write_transcript(tmp_path, [
        task_record("pass1-jurisdiction"),
        task_record("pass3b-citations"),
        task_record("pass7-dissent-crosscheck"),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    assert [r["pass"] for r in rows] == [
        "1 — Jurisdiction", "3B — Citations", "7 — Dissent cross-check",
    ]
    assert rows[0]["model"] == "claude-opus-4-8[1m]"
    assert rows[0]["output"] == 11_807
    assert rows[0]["cache_read"] == 152_790


def test_ignores_unrelated_subagents(tmp_path):
    """A session may hold subagents that are not jetredline passes."""
    other = task_record("pass2-style")
    other["toolUseResult"]["prompt"] = "Search the repo for the cite parser."
    transcript = write_transcript(tmp_path, [other, task_record("pass2-style")])
    rows = provenance.collect_subagent_rows(transcript)
    assert len(rows) == 1
    assert rows[0]["pass"] == "2 — Style"


def test_unknown_pass_stem_is_not_emitted(tmp_path):
    """Only whitelisted stems produce rows, so no unvetted text can reach the table."""
    transcript = write_transcript(tmp_path, [task_record("pass9-experimental")])
    assert provenance.collect_subagent_rows(transcript) == []


# --- pass identification: the two tiers ------------------------------------

def test_tier1_instruction_file_wins():
    assert provenance.identify_pass(pass_prompt("pass3b-citations")) == "3B — Citations"


def test_tier2_matches_the_pre_4_8_0_inline_prompt():
    """Prompts predating references/pass-instructions/ opened in prose."""
    prompt = ("You are running Pass 4 (fact-check) for a jetredline audit of a "
              "North Dakota Supreme Court opinion. The record is at ...")
    assert provenance.identify_pass(prompt) == "4 — Fact check"


def test_tier2_requires_the_skill_name():
    """A bare pass number is too generic to attribute to jetredline."""
    assert provenance.identify_pass("Run Pass 4 of the migration checklist.") is None


def test_tier2_ignores_a_pass_number_late_in_a_long_prompt():
    prompt = "jetredline " + ("filler " * 200) + "Pass 4"
    assert provenance.identify_pass(prompt) is None


def test_tier2_unknown_pass_number_is_not_emitted():
    assert provenance.identify_pass("jetredline audit, Pass 9 (experimental)") is None


def test_identify_pass_on_unrelated_prompt():
    assert provenance.identify_pass("Search the repo for the cite parser.") is None


def test_missing_resolved_model_reads_unknown(tmp_path):
    rec = task_record("pass4-factcheck")
    del rec["toolUseResult"]["resolvedModel"]
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    assert rows[0]["model"] == "unknown"
    assert "| unknown |" in provenance.subagent_table(rows)


def test_non_completed_status_is_flagged(tmp_path):
    rec = task_record("pass6-brief-matching", status="errored")
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    assert rows[0]["status"] == "errored"
    assert "6 — Brief matching (errored)" in provenance.subagent_table(rows)


def test_missing_usage_degrades_to_dashes(tmp_path):
    rec = task_record("pass2-style")
    del rec["toolUseResult"]["usage"]
    del rec["toolUseResult"]["totalToolUseCount"]
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    table = provenance.subagent_table(rows)
    assert "| 2 — Style | claude-opus-4-8[1m] | — | — | — | — |" in table


def test_repeated_pass_yields_both_rows(tmp_path):
    transcript = write_transcript(tmp_path, [
        task_record("pass2-style"), task_record("pass2-style"),
    ])
    assert len(provenance.collect_subagent_rows(transcript)) == 2


# --- failure modes ---------------------------------------------------------

def test_malformed_lines_are_skipped(tmp_path):
    path = tmp_path / "s.jsonl"
    path.write_text(
        '{"agentType": truncated…\n'
        + json.dumps(task_record("pass2-style")) + "\n"
        + "not json at all\n",
        encoding="utf-8",
    )
    rows = provenance.collect_subagent_rows(path)
    assert len(rows) == 1


def test_missing_transcript_returns_empty(tmp_path):
    assert provenance.collect_subagent_rows(tmp_path / "nope.jsonl") == []


def test_tool_use_result_that_is_not_a_dict(tmp_path):
    transcript = write_transcript(tmp_path, [{"toolUseResult": "agentType string"}])
    assert provenance.collect_subagent_rows(transcript) == []


def test_empty_rows_render_no_table():
    assert provenance.subagent_table([]) == ""


def test_find_transcript_with_no_session_id():
    assert provenance.find_transcript("") is None
    assert provenance.find_transcript(None) is None


# --- privacy ---------------------------------------------------------------

def test_no_prompt_or_result_text_reaches_the_report(report, tmp_path):
    """The stamped report goes into the case file: only numbers may cross over."""
    transcript = write_transcript(tmp_path, [
        task_record("pass1-jurisdiction"),
        task_record("pass4-factcheck"),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    text = stamp_it(report, rows)

    assert SECRET not in text
    assert "/cases/" not in text
    assert "pass-instructions" not in text
    assert "findings mentioning" not in text
    # And nothing prompt-derived survives in the row dicts themselves.
    assert not any(SECRET in str(v) for row in rows for v in row.values())


# --- formatting ------------------------------------------------------------

@pytest.mark.parametrize("value,expected", [
    (0, "0"), (2, "2"), (999, "999"), (1000, "1.0k"), (11_807, "11.8k"),
    (152_790, "152.8k"), (1_500_000, "1.5M"), (None, "—"), ("x", "—"),
])
def test_human_token_counts(value, expected):
    assert provenance._human(value) == expected


@pytest.mark.parametrize("value,expected", [
    (0, "0s"), (48_000, "48s"), (201_000, "3m 21s"), (3_930_000, "1h 05m"),
    (None, "—"), ("x", "—"),
])
def test_duration_formatting(value, expected):
    assert provenance._duration(value) == expected
