"""Tests for provenance.py — footer stamping and the delegated-pass table."""

import json

import pytest

import provenance


# --- helpers ---------------------------------------------------------------

SKILL_ROOT = "/Users/x/.claude/skills/jetredline"

# A prompt shaped like the ones SKILL.md builds for a delegated pass. The
# case-identifying text is deliberately distinctive so the leakage test can
# assert it never reaches the stamped report.
SECRET = "Roe-v-Doe-SEALED-FIXTURE"


def pass_prompt(stem, extra=SECRET):
    return (
        f"Read {SKILL_ROOT}/references/pass-instructions/{stem}.md and follow it. "
        f"The skill root is {SKILL_ROOT}. The draft is at /cases/{extra}.docx. "
        "Return only the structured entry list those instructions specify."
    )


def task_record(stem, model="claude-opus-4-8[1m]", **overrides):
    """A synchronous agent's self-contained completion record."""
    result = {
        "agentId": "agent_01",
        "agentType": "general-purpose",
        "content": [{"type": "text", "text": f"findings mentioning {SECRET}"}],
        "prompt": pass_prompt(stem),
        "resolvedModel": model,
        "status": "completed",
        "totalDurationMs": 201_000,
        "totalToolUseCount": 14,
        "totalTokens": 175_922,
        "usage": {
            "input_tokens": 2,
            "output_tokens": 11_807,
            "cache_creation_input_tokens": 11_323,
            "cache_read_input_tokens": 152_790,
        },
    }
    result.update(overrides)
    return {"type": "user", "toolUseResult": result}


# --- background agents: the launch record and its later notification are two
# separate transcript entries, joined on agentId. Shapes copied from a real run.

def launch_record(stem, agent_id="ae6c2d3904330e472", description="Pass 1 jurisdiction check",
                  model="claude-opus-5[1m]", **overrides):
    result = {
        "isAsync": True,
        "status": "async_launched",
        "agentId": agent_id,
        "description": description,
        "resolvedModel": model,
        "prompt": pass_prompt(stem),
        "outputFile": f"/tmp/tasks/{SECRET}/{agent_id}.output",
        "canReadOutputFile": True,
    }
    result.update(overrides)
    return {"type": "user", "toolUseResult": result}


def notification_record(agent_id="ae6c2d3904330e472", tokens=124_136, tools=37,
                        duration_ms=288_504, status="completed", result_text=None):
    usage = ""
    if tokens is not None:
        usage += f"<subagent_tokens>{tokens}</subagent_tokens>"
    if tools is not None:
        usage += f"<tool_uses>{tools}</tool_uses>"
    if duration_ms is not None:
        usage += f"<duration_ms>{duration_ms}</duration_ms>"
    text = (
        "<task-notification>\n"
        f"<task-id>{agent_id}</task-id>\n"
        "<tool-use-id>toolu_01Dzo5w9JKVEDG7u4LWHUFhS</tool-use-id>\n"
        f"<output-file>/tmp/tasks/{SECRET}/{agent_id}.output</output-file>\n"
        f"<status>{status}</status>\n"
        f'<summary>Agent "Pass 1 jurisdiction check" finished</summary>\n'
        f"<result>{result_text or f'Findings about {SECRET} in detail.'}</result>\n"
        f"<usage>{usage}</usage>\n"
        "</task-notification>"
    )
    return {"type": "attachment", "attachment": {"type": "task_notification", "prompt": text}}


def write_transcript(tmp_path, records, name="session.jsonl"):
    path = tmp_path / name
    with open(path, "w", encoding="utf-8") as fh:
        for r in records:
            fh.write(json.dumps(r) + "\n")
    return path


@pytest.fixture
def report(tmp_path):
    path = tmp_path / "OPINION-ANALYSIS.md"
    path.write_text("# Analysis\n\nSome findings.\n", encoding="utf-8")
    return path


def stamp_it(path, rows=None):
    provenance.stamp(path, "Claude Opus 5 (claude-opus-5)", "jetredline",
                     "4.13.0", "2026-08-07", rows)
    return path.read_text(encoding="utf-8")


# --- footer basics ---------------------------------------------------------

def test_stamp_appends_footer(report):
    text = stamp_it(report)
    assert "*Report generated by Claude Opus 5 (claude-opus-5) using jetredline v4.13.0 on 2026-08-07." in text
    assert text.count("Report generated by") == 1
    assert "# Analysis" in text


def test_stamp_is_idempotent_without_table(report):
    stamp_it(report)
    text = stamp_it(report)
    assert text.count("Report generated by") == 1
    assert text.count("---") == 1


def test_stamp_is_idempotent_with_table(report, tmp_path):
    rows = provenance.collect_subagent_rows(
        write_transcript(tmp_path, [task_record("pass2-style")])
    )
    stamp_it(report, rows)
    text = stamp_it(report, rows)
    assert text.count("Report generated by") == 1
    assert text.count("**Delegated passes**") == 1
    assert text.count("| 2 — Style |") == 1


def test_restamping_drops_a_stale_table(report, tmp_path):
    rows = provenance.collect_subagent_rows(
        write_transcript(tmp_path, [task_record("pass2-style")])
    )
    stamp_it(report, rows)
    text = stamp_it(report, [])          # e.g. re-run in a session with no passes
    assert "**Delegated passes**" not in text
    assert text.count("Report generated by") == 1


def test_quoted_footer_sentence_midbody_survives(tmp_path):
    """The regex is end-anchored: a report that quotes a footer isn't truncated."""
    path = tmp_path / "R.md"
    path.write_text(
        "# Analysis\n\n"
        "The prior report ended: *Report generated by Claude Opus 4.8 "
        "(claude-opus-4-8) using jetredline v4.4.0 on 2026-06-05.*\n\n"
        "That footer is quoted, not ours.\n",
        encoding="utf-8",
    )
    text = stamp_it(path)
    assert "That footer is quoted, not ours." in text
    assert text.count("Report generated by") == 2


# --- transcript parsing ----------------------------------------------------

def test_collects_one_row_per_delegated_pass(tmp_path):
    transcript = write_transcript(tmp_path, [
        task_record("pass1-jurisdiction"),
        task_record("pass3b-citations"),
        task_record("pass7-dissent-crosscheck"),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    assert [r["pass"] for r in rows] == [
        "1 — Jurisdiction", "3B — Citations", "7 — Dissent cross-check",
    ]
    assert rows[0]["model"] == "claude-opus-4-8[1m]"
    assert rows[0]["tokens"] == 175_922
    assert rows[0]["tools"] == 14


def test_ignores_unrelated_subagents(tmp_path):
    """A session may hold subagents that are not jetredline passes."""
    other = task_record("pass2-style")
    other["toolUseResult"]["prompt"] = "Search the repo for the cite parser."
    transcript = write_transcript(tmp_path, [other, task_record("pass2-style")])
    rows = provenance.collect_subagent_rows(transcript)
    assert len(rows) == 1
    assert rows[0]["pass"] == "2 — Style"


def test_unknown_pass_stem_is_not_emitted(tmp_path):
    """Only whitelisted stems produce rows, so no unvetted text can reach the table."""
    transcript = write_transcript(tmp_path, [task_record("pass9-experimental")])
    assert provenance.collect_subagent_rows(transcript) == []


# --- pass identification: the two tiers ------------------------------------

def test_tier1_instruction_file_wins():
    assert provenance.identify_pass(pass_prompt("pass3b-citations")) == "3B — Citations"


def test_tier1_knows_every_shipped_pass_file():
    """A pass file without a PASS_LABELS entry vanishes from the usage table."""
    from pathlib import Path
    skill_dir = Path(provenance.__file__).parent
    shipped = sorted(p.stem for p in
                     (skill_dir / "references" / "pass-instructions").glob("pass*.md"))
    assert shipped, "no pass-instruction files found beside provenance.py"
    for stem in shipped:
        assert provenance.identify_pass(pass_prompt(stem)), stem


def test_tier2_supplied_authorities():
    assert provenance.identify_pass(
        "jetredline Pass 3D (supplied authorities): match draft references ..."
    ) == "3D — Supplied authorities"


def test_tier2_matches_the_pre_4_8_0_inline_prompt():
    """Prompts predating references/pass-instructions/ opened in prose."""
    prompt = ("You are running Pass 4 (fact-check) for a jetredline audit of a "
              "North Dakota Supreme Court opinion. The record is at ...")
    assert provenance.identify_pass(prompt) == "4 — Fact check"


def test_tier2_requires_the_skill_name():
    """A bare pass number is too generic to attribute to jetredline."""
    assert provenance.identify_pass("Run Pass 4 of the migration checklist.") is None


def test_tier2_ignores_a_pass_number_late_in_a_long_prompt():
    prompt = "jetredline " + ("filler " * 200) + "Pass 4"
    assert provenance.identify_pass(prompt) is None


def test_tier2_unknown_pass_number_is_not_emitted():
    assert provenance.identify_pass("jetredline audit, Pass 9 (experimental)") is None


def test_identify_pass_on_unrelated_prompt():
    assert provenance.identify_pass("Search the repo for the cite parser.") is None


def test_missing_resolved_model_reads_dash(tmp_path):
    """Synchronous records omit resolvedModel entirely."""
    rec = task_record("pass4-factcheck")
    del rec["toolUseResult"]["resolvedModel"]
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    assert rows[0]["model"] == "—"
    assert "| 4 — Fact check | — |" in provenance.subagent_table(rows)


def test_token_total_falls_back_to_summing_usage(tmp_path):
    rec = task_record("pass2-style")
    del rec["toolUseResult"]["totalTokens"]
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    assert rows[0]["tokens"] == 2 + 11_807 + 11_323 + 152_790


def test_non_completed_status_is_flagged(tmp_path):
    rec = task_record("pass6-brief-matching", status="errored")
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    assert rows[0]["status"] == "errored"
    assert "6 — Brief matching (errored)" in provenance.subagent_table(rows)


def test_missing_usage_degrades_to_dashes(tmp_path):
    rec = task_record("pass2-style")
    for field in ("usage", "totalTokens", "totalToolUseCount", "totalDurationMs"):
        del rec["toolUseResult"][field]
    rows = provenance.collect_subagent_rows(write_transcript(tmp_path, [rec]))
    table = provenance.subagent_table(rows)
    assert "| 2 — Style | claude-opus-4-8[1m] | — | — | — |" in table


# --- background agents: launch record joined to its notification -------------

def test_background_agent_row_joins_launch_and_notification(tmp_path):
    transcript = write_transcript(tmp_path, [
        launch_record("pass1-jurisdiction"),
        notification_record(),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    assert len(rows) == 1
    assert rows[0] == {
        "pass": "1 — Jurisdiction",
        "model": "claude-opus-5[1m]",
        "tokens": 124_136,
        "tools": 37,
        "duration_ms": 288_504,
        "status": None,
    }
    assert ("| 1 — Jurisdiction | claude-opus-5[1m] | 124.1k | 37 | 4m 48s |"
            in provenance.subagent_table(rows))


def test_background_agent_still_running_is_dropped(tmp_path):
    """No notification yet: an in-flight agent contributes no row."""
    transcript = write_transcript(tmp_path, [launch_record("pass1-jurisdiction")])
    assert provenance.collect_subagent_rows(transcript) == []


def test_notification_without_a_launch_is_ignored(tmp_path):
    transcript = write_transcript(tmp_path, [notification_record()])
    assert provenance.collect_subagent_rows(transcript) == []


def test_resumed_agent_uses_its_last_notification(tmp_path):
    """A task-id may notify more than once; the final figures are cumulative."""
    transcript = write_transcript(tmp_path, [
        launch_record("pass4-factcheck"),
        notification_record(tokens=50_000, tools=10, duration_ms=60_000),
        notification_record(tokens=124_136, tools=37, duration_ms=288_504),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    assert len(rows) == 1
    assert rows[0]["tokens"] == 124_136


def test_background_agents_join_on_their_own_ids(tmp_path):
    transcript = write_transcript(tmp_path, [
        launch_record("pass1-jurisdiction", agent_id="a1"),
        launch_record("pass4-factcheck", agent_id="a2"),
        notification_record(agent_id="a2", tokens=111_400, tools=29, duration_ms=566_000),
        notification_record(agent_id="a1", tokens=124_136, tools=37, duration_ms=288_504),
    ])
    rows = {r["pass"]: r for r in provenance.collect_subagent_rows(transcript)}
    assert rows["1 — Jurisdiction"]["tokens"] == 124_136
    assert rows["4 — Fact check"]["tokens"] == 111_400


def test_failed_background_agent_is_flagged(tmp_path):
    transcript = write_transcript(tmp_path, [
        launch_record("pass6-brief-matching"),
        notification_record(status="failed"),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    assert rows[0]["status"] == "failed"
    assert "1 — Jurisdiction (failed)" not in provenance.subagent_table(rows)
    assert "6 — Brief matching (failed)" in provenance.subagent_table(rows)


def test_notification_missing_usage_fields_degrades(tmp_path):
    transcript = write_transcript(tmp_path, [
        launch_record("pass2-style"),
        notification_record(tokens=None, tools=None, duration_ms=None),
    ])
    table = provenance.subagent_table(provenance.collect_subagent_rows(transcript))
    assert "| 2 — Style | claude-opus-5[1m] | — | — | — |" in table


# --- tier 3: the agent's display label --------------------------------------

def test_description_labels_an_agent_the_prompt_cannot_identify(tmp_path):
    """Sibling skills delegate un-numbered agents; the launch description names them."""
    rec = launch_record("pass1-jurisdiction", description="Agent D precedent lookup")
    rec["toolUseResult"]["prompt"] = "Verify these citations against the record."
    transcript = write_transcript(tmp_path, [rec, notification_record()])
    rows = provenance.collect_subagent_rows(transcript)
    assert rows[0]["pass"] == "Agent D precedent lookup"


def test_pass_identification_outranks_the_description(tmp_path):
    rec = launch_record("pass1-jurisdiction", description="something vague")
    transcript = write_transcript(tmp_path, [rec, notification_record()])
    assert provenance.collect_subagent_rows(transcript)[0]["pass"] == "1 — Jurisdiction"


def test_agent_with_neither_marker_is_dropped(tmp_path):
    rec = launch_record("pass1-jurisdiction", description="")
    rec["toolUseResult"]["prompt"] = "Search the repo for the cite parser."
    transcript = write_transcript(tmp_path, [rec, notification_record()])
    assert provenance.collect_subagent_rows(transcript) == []


@pytest.mark.parametrize("raw,expected", [
    ("Pass 4 fact check", "Pass 4 fact check"),
    ("  Pass 4   fact\ncheck  ", "Pass 4 fact check"),
    ("**Pass 4** <b>fact</b> check", "Pass 4 b fact /b check"),
    ("| injected | table | row |", "injected table row"),
    ("", None),
    ("   ", None),
    (None, None),
    (42, None),
])
def test_description_is_sanitised(raw, expected):
    assert provenance._clean_description(raw) == expected


def test_long_description_is_truncated():
    cleaned = provenance._clean_description("Pass " + "x" * 200)
    assert len(cleaned) <= provenance._DESC_MAX
    assert cleaned.endswith("…")


def test_description_cannot_break_the_table(tmp_path):
    """A pipe in a description would otherwise forge extra columns."""
    rec = launch_record("pass9-unknown", description="evil | col | col")
    rec["toolUseResult"]["prompt"] = "no pass marker here"
    transcript = write_transcript(tmp_path, [rec, notification_record()])
    body = provenance.subagent_table(provenance.collect_subagent_rows(transcript)).splitlines()[-1]
    assert body.count("|") == 6          # 5 columns => 6 delimiters, no more
    assert "evil col col" in body


def test_repeated_pass_yields_both_rows(tmp_path):
    transcript = write_transcript(tmp_path, [
        task_record("pass2-style"), task_record("pass2-style"),
    ])
    assert len(provenance.collect_subagent_rows(transcript)) == 2


# --- failure modes ---------------------------------------------------------

def test_malformed_lines_are_skipped(tmp_path):
    path = tmp_path / "s.jsonl"
    path.write_text(
        '{"agentType": truncated…\n'
        + json.dumps(task_record("pass2-style")) + "\n"
        + "not json at all\n",
        encoding="utf-8",
    )
    rows = provenance.collect_subagent_rows(path)
    assert len(rows) == 1


def test_missing_transcript_returns_empty(tmp_path):
    assert provenance.collect_subagent_rows(tmp_path / "nope.jsonl") == []


def test_tool_use_result_that_is_not_a_dict(tmp_path):
    transcript = write_transcript(tmp_path, [{"toolUseResult": "agentType string"}])
    assert provenance.collect_subagent_rows(transcript) == []


def test_empty_rows_render_no_table():
    assert provenance.subagent_table([]) == ""


def test_find_transcript_with_no_session_id():
    assert provenance.find_transcript("") is None
    assert provenance.find_transcript(None) is None


# --- privacy ---------------------------------------------------------------

def test_no_prompt_or_result_text_reaches_the_report(report, tmp_path):
    """The stamped report goes into the case file: only numbers may cross over."""
    transcript = write_transcript(tmp_path, [
        task_record("pass1-jurisdiction"),
        task_record("pass4-factcheck"),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    text = stamp_it(report, rows)

    assert SECRET not in text
    assert "/cases/" not in text
    assert "pass-instructions" not in text
    assert "findings mentioning" not in text
    # And nothing prompt-derived survives in the row dicts themselves.
    assert not any(SECRET in str(v) for row in rows for v in row.values())


def test_background_notification_findings_never_reach_the_report(report, tmp_path):
    """A notification embeds the agent's full <result> — the case analysis itself."""
    transcript = write_transcript(tmp_path, [
        launch_record("pass1-jurisdiction"),
        notification_record(result_text=(
            "## Pass 1 findings\n\nR31 terminating parental rights was entered "
            f"June 12, 2026 in {SECRET}; the appeal is timely by one day."
        )),
    ])
    rows = provenance.collect_subagent_rows(transcript)
    text = stamp_it(report, rows)

    assert rows and rows[0]["tokens"] == 124_136      # the row was in fact built
    for leaked in (SECRET, "parental rights", "June 12", "timely", "/tmp/tasks",
                   "toolu_", "output-file", "task-notification"):
        assert leaked not in text


# --- formatting ------------------------------------------------------------

@pytest.mark.parametrize("value,expected", [
    (0, "0"), (2, "2"), (999, "999"), (1000, "1.0k"), (11_807, "11.8k"),
    (152_790, "152.8k"), (1_500_000, "1.5M"), (None, "—"), ("x", "—"),
])
def test_human_token_counts(value, expected):
    assert provenance._human(value) == expected


@pytest.mark.parametrize("value,expected", [
    (0, "0s"), (48_000, "48s"), (201_000, "3m 21s"), (3_930_000, "1h 05m"),
    (None, "—"), ("x", "—"),
])
def test_duration_formatting(value, expected):
    assert provenance._duration(value) == expected
