"""Tests for analysis_to_html.py — the -ANALYSIS.md → HTML renderer."""

import re
import shutil
import subprocess

import pytest

from analysis_to_html import (
    build_page,
    classify_file_cell,
    classify_status,
    coverage_misses,
    parse_blocks,
    render_inline,
)


# A report exercising every construct the template and real runs produce:
# H1 title, an alert section, tables with each status vocabulary, a wide
# table, a blockquote, ordered and unordered lists, a checkbox worklist,
# links and code spans in cells, and the provenance footer.
SAMPLE = """# JetRedline Analysis — *Doe v. Roe*, No. 20990001

–Begin Analysis–

## Case Highlight

**Doe v. Roe, 2026 ND 1**
**Disposition:** Affirmed.

## ⚠ Source Materials Not Reviewed

| File | Reason | Passes affected | Remediation |
|---|---|---|---|
| reply.pdf | image-only / no text layer | Pass 4, Pass 6 | re-OCR |

**Inputs ingested: 3 of 4.**

## Fact Check

| ¶ | Claim | Source Document(s) | Result | Notes |
|---|-------|-------------------|--------|-------|
| 2 | Filing date | R1 | Verified | Clean. |
| 3 | Hearing date | R4 | Discrepancy | Order says March 4. |
| 4 | Service | R9 | Unverified | Not in the record. |
| 5 | Venue | R2 | Verified (verbatim) | |
| 6 | Amount | R7 | Verified | |

**Summary:** 5 facts checked.

## Brief Matching

| ¶ | Argument | Party | Brief Source | Addressed | Notes |
|---|----------|-------|-------------|-----------|-------|
| 7 | Waiver | Appellant | App. Br. pp. 3–5 | Yes | Fully analyzed. |
| 8 | Standing | Appellee | Ape. Br. p. 9 | Partial | Recited only. |
| 9 | Mootness | Appellant | App. Br. p. 12 | No | Not reached. |

## Citation Verification

| ¶ | Citation | Type | Quote Check | Supports? | Source Link | Notes |
|---|----------|------|-------------|-----------|-------------|-------|
| 8 | *State v. Martinez*, 2015 ND 173, ¶ 31 | Opinion | No quote | Supports | [2015 ND 173](https://www.ndcourts.gov/x/1) | Paraphrase. |
| 9 | **`Id. At`** capital form | Opinion | **Discrepancy — corrected** | Does not support | same | Fixed. |
| 10 | N.D.R.Ev. 412(a) | Rule | Verified (verbatim) | Supports | [Rule 412](https://www.ndcourts.gov/rules/412) | |

## Supplied Authorities

| ¶ | Authority | Kind | Cited page | Matched file | Page check | Quote check | Supports? | Notes |
|---|-----------|------|------------|--------------|------------|-------------|-----------|-------|
| 4 | *Treatise on X* | treatise | 220 | **none found** | N/A | Not found | Partially | Obtain a copy. |

**Authorities relied on but not located:**
- [ ] *Treatise on X* (¶ 4) — no copy in the case directory.
- [x] *Journal Article* (¶ 6) — obtained.

## Substantive Concerns

### Potential Dicta

1. **¶23 — "waived and without merit."** Two inconsistent dispositions.

2. **¶25 — remaining issues.** Standard formulation.

> **Note:** the district court's order at R66 controls.

## Style Notes

- Serial comma applied throughout.
- `¶ ` spacing normalized.

---
*Claude skills crafted by Claude and JET (github.com/jet52)*

*Report generated by Claude Opus 5 (claude-opus-5) using jetredline v4.22.0 on 2026-08-24. AI-generated first draft for internal use; verify all citations and findings before relying.*

–End Analysis–
"""


@pytest.fixture(scope="module")
def page():
    return build_page(SAMPLE)


class TestInline:
    def test_bold_and_italic(self):
        assert render_inline("*Doe*") == "<em>Doe</em>"
        assert render_inline("**hi**") == "<strong>hi</strong>"

    def test_emphasis_spans_a_code_token(self):
        """``**`Id. At`**`` must bold — the token can't break the pair."""
        out = render_inline("**`Id. At`** capital")
        assert out.startswith("<strong><code>Id. At</code></strong>")

    def test_link_renders_with_href(self):
        out = render_inline("[2015 ND 173](https://www.ndcourts.gov/x/1)")
        assert '<a href="https://www.ndcourts.gov/x/1"' in out
        assert ">2015 ND 173</a>" in out

    def test_link_url_with_balanced_parens(self):
        out = render_inline("[Foo](https://ex.org/a_(b))")
        assert 'href="https://ex.org/a_(b)"' in out

    def test_unsafe_scheme_becomes_plain_text(self):
        out = render_inline("[bad](javascript:alert)")
        assert "javascript" not in out
        assert "<a " not in out
        assert "bad" in out

    def test_html_is_escaped(self):
        assert "<script>" not in render_inline("<script>alert(1)</script>")

    def test_unpaired_asterisk_is_literal(self):
        assert render_inline("the *236 break") == "the *236 break"


class TestStatusClassification:
    @pytest.mark.parametrize("cell,kind", [
        ("Verified", "ok"),
        ("Verified (verbatim)", "ok"),
        ("Yes", "ok"),
        ("Supports", "ok"),
        ("Partial", "caution"),
        ("Partially", "caution"),
        ("No quote", "caution"),
        ("Unverified", "caution"),
        ("Discrepancy", "problem"),
        ("**Discrepancy — corrected**", "problem"),
        ("Does not support", "problem"),
        ("Not found", "problem"),
        ("No", "problem"),
        ("N/A", "neutral"),
        ("", "neutral"),
        ("—", "neutral"),
    ])
    def test_vocabulary(self, cell, kind):
        assert classify_status(cell) == kind

    def test_unverified_beats_verified(self):
        assert classify_status("Unverified") == "caution"

    def test_no_quote_beats_bare_no(self):
        assert classify_status("No quote") == "caution"

    def test_matched_file(self):
        assert classify_file_cell("**none found**") == "problem"
        assert classify_file_cell("treatise_p220.pdf") == "neutral"


class TestParsing:
    def test_sentinels_are_dropped(self):
        kinds = [b["kind"] for b in parse_blocks(SAMPLE.split("\n"))]
        assert "heading" in kinds and "table" in kinds
        assert "–Begin Analysis–" not in build_page(SAMPLE)

    def test_tables_found(self):
        tables = [b for b in parse_blocks(SAMPLE.split("\n"))
                  if b["kind"] == "table"]
        assert len(tables) == 5
        assert len(tables[1]["rows"]) == 5          # Fact Check

    def test_task_items(self):
        lists = [b for b in parse_blocks(SAMPLE.split("\n"))
                 if b["kind"] == "list"]
        tasks = [i for b in lists for i in b["items"] if i["task"]]
        assert len(tasks) == 2
        assert [t["done"] for t in tasks] == [False, True]

    def test_blockquote(self):
        assert any(b["kind"] == "quote" for b in parse_blocks(SAMPLE.split("\n")))

    def test_escaped_pipe_in_cell(self):
        blocks = parse_blocks(["| a | b |", "|---|---|", r"| x \| y | z |"])
        assert blocks[0]["rows"][0] == ["x | y", "z"]


class TestPage:
    def test_title_from_h1(self, page):
        assert "<title>JetRedline Analysis — Doe v. Roe, No. 20990001</title>" in page

    def test_self_contained(self, page):
        """No external fetches: the file must work offline and in Cowork."""
        for bad in ("src=\"http", "href=\"http://cdn", "<link rel=\"stylesheet\"",
                    "@import"):
            assert bad not in page
        assert page.count("<style>") == 1 and page.count("<script>") == 1

    def test_toc_lists_sections(self, page):
        assert 'class="toc"' in page
        for title in ("Fact Check", "Brief Matching", "Citation Verification"):
            assert f">{title}</span>" in page

    def test_section_ids_are_unique(self, page):
        ids = re.findall(r'<section id="([^"]+)"', page)
        assert ids and len(ids) == len(set(ids))

    def test_badges_carry_glyph_and_label(self, page):
        """Color is never load-bearing — every badge has a glyph and its text."""
        for cls, gly in (("b-ok", "✓"), ("b-caution", "◐"), ("b-problem", "✗")):
            m = re.search(f'<span class="badge {cls}">'
                          r'<span class="gly" aria-hidden="true">(.)</span>', page)
            assert m, f"no {cls} badge emitted"
            assert m.group(1) == gly

    def test_row_status_marks_worst_cell(self, page):
        assert 'data-status="problem"' in page
        assert 'data-status="caution"' in page
        assert 'data-status="ok"' in page

    def test_banner_counts_flagged_rows(self, page):
        # Discrepancy, No, Does not support, none-found → 4 problem rows.
        m = re.search(r'<span class="tally problem"><span class="v">(\d+)</span>', page)
        assert m and int(m.group(1)) == 4

    def test_alert_section_promoted(self, page):
        assert 'class="alert"' in page
        assert "⚠ Source Materials Not Reviewed" in page

    def test_wide_table_class(self, page):
        assert "table class=\"md wide\"" in page      # 7- and 9-column tables

    def test_problems_only_control_present(self, page):
        assert "tbl-only" in page and "tbl-filter" in page

    def test_provenance_moves_to_footer(self, page):
        foot = page[page.index('<footer class="report">'):]
        assert "Report generated by Claude Opus 5" in foot
        assert "crafted by Claude and JET" in foot

    def test_print_stylesheet(self, page):
        assert "@media print" in page and "table-header-group" in page

    def test_cite_review_link(self):
        p = build_page(SAMPLE, cite_review="Doe-CITE-REVIEW.html")
        assert 'href="Doe-CITE-REVIEW.html"' in p

    def test_title_override(self):
        assert "<title>Custom</title>" in build_page(SAMPLE, title="Custom")

    def test_light_only_no_dark_media_query(self, page):
        """Deliberately light-only: it is a document, and it is what prints."""
        assert "prefers-color-scheme" not in page


class TestCoverage:
    def test_sample_loses_nothing(self, page):
        assert coverage_misses(SAMPLE, page) == []

    def test_check_detects_a_real_loss(self, page):
        """The invariant has teeth: add a line and the check must notice."""
        doctored = SAMPLE + "\n## Orphan Section\n\nA sentence that never renders.\n"
        stale = page          # rendered before the addition
        misses = coverage_misses(doctored, stale)
        assert any("never renders" in probe for _, probe in misses)

    def test_real_report_shapes(self):
        """Headings and tables the template does not specify still render."""
        odd = ("## Custom Section\n\n"
               "| Element | Finding | Confidence |\n|---|---|---|\n"
               "| Notice | present | high |\n\n"
               "1. One item.\n\n2. Another item.\n")
        assert coverage_misses(odd, build_page(odd)) == []


class TestEmittedJavaScript:
    def test_parses(self, page, tmp_path):
        node = shutil.which("node")
        if not node:
            pytest.skip("node not on PATH")
        scripts = re.findall(r"<script>(.*?)</script>", page, re.S)
        assert scripts
        f = tmp_path / "emitted.js"
        f.write_text(scripts[0], encoding="utf-8")
        r = subprocess.run([node, "--check", str(f)],
                           capture_output=True, text=True)
        assert r.returncode == 0, f"emitted <script> is invalid:\n{r.stderr}"


class TestCli:
    def test_writes_sibling_html(self, tmp_path):
        import sys
        src = tmp_path / "Case_Opinion-ANALYSIS.md"
        src.write_text(SAMPLE, encoding="utf-8")
        r = subprocess.run(
            [sys.executable,
             str(__import__("pathlib").Path(__file__).resolve().parent.parent
                 / "skills" / "jetredline" / "analysis_to_html.py"),
             str(src), "--check"],
            capture_output=True, text=True)
        assert r.returncode == 0, r.stderr
        out = tmp_path / "Case_Opinion-ANALYSIS.html"
        assert out.is_file()
        assert "coverage check passed" in r.stdout
        assert "5 tables" in r.stdout
