#!/usr/bin/env python3
"""Stamp a provenance footer onto a generated report.

Shared across jet52 projects: jetmemo, jetredline, jetbriefcheck, jetrehearing.

The footer records, for later validation and comparison as the tools and the
Claude models change:
    Report generated by <model> using <skill> v<version> on <YYYY-MM-DD>.

Design: the parts that can be sourced deterministically *are* — the skill
version (from SKILL.md frontmatter `version:`, then a VERSION file) and the
date (the system clock). The model identifier is supplied by the caller (the
orchestrator, which alone knows the runtime model); this script never guesses
the model, because a model naming its own release is exactly the unreliable
self-report a validation record must not depend on.

With --subagents, the footer also carries a table of the delegated passes: the
model each subagent actually ran on and what it consumed. That comes from the
session transcript, not from the orchestrator's self-report — see
collect_subagent_rows() for the mechanism and its caveats.

Idempotent: re-running replaces an existing footer (table included) rather than
appending a duplicate, so it is safe to call on every regeneration.

Usage:
    python3 provenance.py --file REPORT.md --model "Claude Opus 4.8 (claude-opus-4-8)"
    python3 provenance.py --file REPORT.md --model "..." --subagents
    # optional: --date YYYY-MM-DD (defaults to today), --skill NAME, --skill-dir DIR

The skill name and version are derived from this script's own location
(<skill>/scripts/provenance.py), matching check_update.py, so the orchestrator
normally needs to pass only --file and --model.
"""

import argparse
import json
import os
import re
import sys
from datetime import date
from glob import glob
from pathlib import Path

# Per-skill constant (like check_update.py). The skill directory may be a
# symlink to a dev checkout whose folder is not named after the skill, so the
# name is hardcoded rather than derived from the path.
SKILL_NAME = "jetredline"

# Matches a previously stamped footer (with or without the leading rule, and
# with or without the delegated-pass table) at end of file, so re-stamping
# replaces rather than duplicates it. Anchored at end so that a report merely
# *quoting* a footer sentence mid-document is never truncated.
_FOOTER_RE = re.compile(
    r"\n*(?:---\s*\n+)?"
    r"\*Report generated by .+? using .+? on .+?\*"
    r"(?:\s*\n+\*\*Delegated passes\*\*\s*\n.*?)?"
    r"\s*$",
    re.S,
)

# --- delegated-pass usage ---------------------------------------------------
#
# Identifying which pass a subagent ran, in three tiers.
#
# Tier 1 (authoritative): since v4.8.0 every delegated pass is launched with a
# prompt that begins "Read <skill root>/references/pass-instructions/passN-*.md
# and follow it", so the instruction-file stem names the pass exactly.
#
# Tier 2 (fallback): older prompts inlined the instructions and opened with
# "You are running Pass 4 (fact-check) for a jetredline audit...", and a
# paraphrased prompt may do the same. A bare pass number is too generic to
# trust alone, so tier 2 also requires the prompt to name the skill.
#
# Tiers 1 and 2 resolve to a fixed label table -- no prompt text reaches the
# report. Tier 3 (see row_label) falls back to the launch record's short
# `description`, which is the orchestrator's own display label for the agent
# ("Pass 4 fact check"), not analysis text; it is sanitised to one short plain
# line. That tier is what lets sibling skills with un-numbered analysis agents
# (jetmemo, jetrehearing) render a table at all.
_PASS_FILE_RE = re.compile(r"pass-instructions/(pass\d+[a-z]?-[a-z0-9-]+)\.md", re.I)
_PASS_PROSE_RE = re.compile(r"\bPass\s+(\d+[AB]?)\b", re.I)
_PROSE_SCAN_CHARS = 400

# Column header for the first column, and the noun used in the heading. Sibling
# skills delegate un-numbered analysis agents rather than numbered passes.
ROW_LABEL = "Pass"
_DESC_MAX = 60
_DESC_SAFE_RE = re.compile(r"[^\w .,:;()/&'-]+")

PASS_LABELS = {
    "pass1-jurisdiction": "1 — Jurisdiction",
    "pass2-style": "2 — Style",
    "pass3b-citations": "3B — Citations",
    "pass4-factcheck": "4 — Fact check",
    "pass6-brief-matching": "6 — Brief matching",
    "pass7-dissent-crosscheck": "7 — Dissent cross-check",
}

PASS_NUMBER_LABELS = {
    "1": "1 — Jurisdiction",
    "2": "2 — Style",
    "3A": "3A — Citation format",
    "3B": "3B — Citations",
    "4": "4 — Fact check",
    "5": "5 — Analytical rigor",
    "6": "6 — Brief matching",
    "7": "7 — Dissent cross-check",
}


def identify_pass(prompt: str):
    """Label for the pass this prompt delegated, or None if it isn't one."""
    if not isinstance(prompt, str):
        return None
    match = _PASS_FILE_RE.search(prompt)
    if match:
        return PASS_LABELS.get(match.group(1).lower())
    if SKILL_NAME not in prompt.lower():
        return None
    match = _PASS_PROSE_RE.search(prompt[:_PROSE_SCAN_CHARS])
    if match:
        return PASS_NUMBER_LABELS.get(match.group(1).upper())
    return None


def _clean_description(description):
    """One short plain line from an agent's display label, or None."""
    if not isinstance(description, str):
        return None
    text = _DESC_SAFE_RE.sub(" ", description).strip()
    text = re.sub(r"\s+", " ", text)
    if not text:
        return None
    return text if len(text) <= _DESC_MAX else text[: _DESC_MAX - 1].rstrip() + "…"


def row_label(prompt, description):
    """Best available label for a delegated agent, or None to drop the row."""
    return identify_pass(prompt) or _clean_description(description)


_TABLE_HEADING = "**Delegated passes**"


def find_transcript(session_id: str):
    """Path to the session transcript, or None.

    Session IDs are UUIDs and unique across projects, so globbing every project
    directory beats reconstructing Claude Code's cwd-to-slug encoding.
    """
    if not session_id:
        return None
    matches = glob(
        os.path.expanduser(f"~/.claude/projects/*/{session_id}.jsonl")
    )
    return Path(matches[0]) if matches else None


def _human(n) -> str:
    """Compact token count: 2, 4.1k, 152.8k, 1.2M."""
    try:
        n = int(n)
    except (TypeError, ValueError):
        return "—"
    if n < 1000:
        return str(n)
    if n < 1_000_000:
        return f"{n / 1000:.1f}k"
    return f"{n / 1_000_000:.1f}M"


def _duration(ms) -> str:
    """Compact wall time: 48s, 3m 21s, 1h 04m."""
    try:
        secs = int(ms) // 1000
    except (TypeError, ValueError):
        return "—"
    if secs < 60:
        return f"{secs}s"
    if secs < 3600:
        return f"{secs // 60}m {secs % 60:02d}s"
    return f"{secs // 3600}h {(secs % 3600) // 60:02d}m"


# A background agent's completion arrives as a <task-notification> block whose
# <task-id> is the launch record's agentId.
_NOTIF_ID_RE = re.compile(r"<task-id>\s*([A-Za-z0-9_-]+)\s*</task-id>")
_NOTIF_STATUS_RE = re.compile(r"<status>\s*([a-z_]+)\s*</status>", re.I)
_NOTIF_TOKENS_RE = re.compile(r"<subagent_tokens>\s*(\d+)\s*</subagent_tokens>")
_NOTIF_TOOLS_RE = re.compile(r"<tool_uses>\s*(\d+)\s*</tool_uses>")
_NOTIF_MS_RE = re.compile(r"<duration_ms>\s*(\d+)\s*</duration_ms>")


def _int_or_none(match):
    return int(match.group(1)) if match else None


def _sum_usage(usage):
    """Total tokens across a legacy `usage` dict, or None."""
    if not isinstance(usage, dict):
        return None
    parts = [
        usage.get(k)
        for k in (
            "input_tokens",
            "output_tokens",
            "cache_creation_input_tokens",
            "cache_read_input_tokens",
        )
    ]
    nums = [p for p in parts if isinstance(p, int)]
    return sum(nums) if nums else None


def collect_subagent_rows(transcript_path) -> list:
    """Per-pass model and usage, read from the session transcript.

    Two record shapes exist and both are handled, because which one a run
    produces depends only on whether its agents ran in the background:

    * Synchronous (`run_in_background: false`) -- one `toolUseResult` carrying
      `agentType`, `prompt`, `usage`/`totalTokens`, `totalToolUseCount` and
      `totalDurationMs`. Self-contained; no `resolvedModel`.

    * Background (the default since ~2026-07) -- the record is split in two.
      The launch `toolUseResult` has `isAsync`, `status: "async_launched"`,
      `agentId`, `description`, `prompt` and `resolvedModel`, but no usage,
      because nothing has run yet. Completion arrives later as an attachment
      holding a `<task-notification>` whose `<task-id>` is that `agentId` and
      whose `<usage>` block reports `subagent_tokens`, `tool_uses` and
      `duration_ms`. The two halves are joined here on the agent id.

      Note the notification reports a single token total -- there is no
      input/output/cache breakdown -- which is why the rendered table is
      token-total only for both shapes.

    An agent may notify more than once (it can be resumed); the last
    notification wins. Agents that never notified are dropped, so an in-flight
    or abandoned agent contributes no row.

    All of this is an internal format with no compatibility guarantee, so every
    field is optional and any failure yields an empty list -- a missing table,
    never a failed run.

    Privacy: prompts are read only to identify the pass against a fixed label
    table, and `description` is the orchestrator's own short display label. No
    prompt body or result text is ever returned, because the stamped report
    goes into the case file.
    """
    launches = []          # background agents, in launch order
    notifications = {}     # agentId -> parsed <task-notification>
    rows = []              # synchronous agents, in completion order
    try:
        with open(transcript_path, "r", encoding="utf-8") as fh:
            for line in fh:
                # Cheap prefilter -- transcripts run to hundreds of thousands
                # of lines and only a handful concern subagents.
                if '"agentType"' not in line and '"agentId"' not in line \
                        and "task-notification" not in line:
                    continue
                try:
                    record = json.loads(line)
                except ValueError:
                    continue

                # --- completion notification (background) ---
                if record.get("type") == "attachment":
                    attachment = record.get("attachment")
                    if not isinstance(attachment, dict):
                        continue
                    text = attachment.get("prompt")
                    if not isinstance(text, str) or "<task-notification>" not in text:
                        continue
                    ident = _NOTIF_ID_RE.search(text)
                    if not ident:
                        continue
                    status = _NOTIF_STATUS_RE.search(text)
                    notifications[ident.group(1)] = {
                        "tokens": _int_or_none(_NOTIF_TOKENS_RE.search(text)),
                        "tools": _int_or_none(_NOTIF_TOOLS_RE.search(text)),
                        "duration_ms": _int_or_none(_NOTIF_MS_RE.search(text)),
                        "status": status.group(1).lower() if status else None,
                    }
                    continue

                result = record.get("toolUseResult")
                if not isinstance(result, dict):
                    continue
                label = row_label(result.get("prompt"), result.get("description"))
                if not label:
                    continue

                # --- background launch: defer until its notification is seen ---
                if result.get("isAsync") or result.get("status") == "async_launched":
                    agent_id = result.get("agentId")
                    if agent_id:
                        launches.append((agent_id, label,
                                         result.get("resolvedModel") or "—"))
                    continue

                # --- synchronous completion: self-contained ---
                if "agentType" not in result:
                    continue
                status = result.get("status")
                tokens = result.get("totalTokens")
                if not isinstance(tokens, int):
                    tokens = _sum_usage(result.get("usage"))
                rows.append(
                    {
                        "pass": label,
                        "model": result.get("resolvedModel") or "—",
                        "tokens": tokens,
                        "tools": result.get("totalToolUseCount"),
                        "duration_ms": result.get("totalDurationMs"),
                        "status": status if status != "completed" else None,
                    }
                )
    except (OSError, ValueError):
        return []

    for agent_id, label, model in launches:
        notification = notifications.get(agent_id)
        if not notification:
            continue  # still running, or never reported
        status = notification.get("status")
        rows.append(
            {
                "pass": label,
                "model": model,
                "tokens": notification.get("tokens"),
                "tools": notification.get("tools"),
                "duration_ms": notification.get("duration_ms"),
                "status": status if status != "completed" else None,
            }
        )
    return rows


def subagent_table(rows: list) -> str:
    """Render the delegated-pass rows as a markdown table (empty string if none).

    Token-total only: background agents report a single `subagent_tokens`
    figure with no input/output/cache breakdown, so a wider schema could not be
    filled for the common case.
    """
    if not rows:
        return ""
    lines = [
        _TABLE_HEADING,
        "",
        f"| {ROW_LABEL} | Model | Tokens | Tools | Time |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        label = r["pass"]
        if r.get("status"):
            label += f" ({r['status']})"
        tools = r.get("tools")
        lines.append(
            "| {} | {} | {} | {} | {} |".format(
                label,
                r["model"],
                _human(r.get("tokens")),
                tools if isinstance(tools, int) else "—",
                _duration(r.get("duration_ms")),
            )
        )
    return "\n".join(lines)


def find_skill_dir(script_path: Path) -> Path:
    """Locate the skill root (holding SKILL.md / VERSION) from this script's path.

    Works whether the script lives in <skill>/scripts/ (jetmemo, jetrehearing)
    or directly in <skill>/ (jetredline). Resolves symlinks first, so a skill
    mounted as a symlink to a dev checkout still resolves correctly.
    """
    here = script_path.resolve()
    for d in (here.parent, here.parent.parent, here.parent.parent.parent):
        if (d / "SKILL.md").exists() or (d / "VERSION").exists():
            return d
    return here.parent.parent


def read_version(skill_dir: Path) -> str:
    """Authoritative version: SKILL.md frontmatter `version:`, then VERSION file."""
    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        m = re.search(r"^version:\s*(.+?)\s*$", skill_md.read_text(), re.M)
        if m:
            return m.group(1).strip().strip("'\"")
    version_file = skill_dir / "VERSION"
    if version_file.exists():
        return version_file.read_text().strip()
    return "unknown"


def footer_line(model: str, skill: str, version: str, on_date: str) -> str:
    ver = f"v{version}" if version != "unknown" else "version unknown"
    return (
        f"*Report generated by {model} using {skill} {ver} on {on_date}. "
        f"AI-generated first draft for internal use; verify all citations and "
        f"findings before relying.*"
    )


def stamp(path: Path, model: str, skill: str, version: str, on_date: str,
          rows: list = None) -> None:
    text = path.read_text().rstrip()
    text = _FOOTER_RE.sub("", text).rstrip()
    footer = footer_line(model, skill, version, on_date)
    table = subagent_table(rows or [])
    if table:
        footer += "\n\n" + table
    path.write_text(text + "\n\n---\n\n" + footer + "\n")


def main() -> int:
    default_skill_dir = find_skill_dir(Path(__file__))

    ap = argparse.ArgumentParser(description="Stamp a provenance footer onto a report.")
    ap.add_argument("--file", required=True, help="Report file to stamp (markdown).")
    ap.add_argument("--model", required=True,
                    help='Runtime model identifier, e.g. "Claude Opus 4.8 (claude-opus-4-8)".')
    ap.add_argument("--skill", default=SKILL_NAME,
                    help="Skill name (defaults to this skill's SKILL_NAME constant).")
    ap.add_argument("--skill-dir", default=str(default_skill_dir),
                    help="Skill root holding SKILL.md / VERSION (defaults to this script's skill).")
    ap.add_argument("--date", default=date.today().isoformat(),
                    help="Generation date YYYY-MM-DD (defaults to today).")
    ap.add_argument("--subagents", action="store_true",
                    help="Append a table of the delegated passes (model and token "
                         "usage per pass), read from this session's transcript.")
    ap.add_argument("--transcript", default=None,
                    help="Transcript path to read instead of locating this "
                         "session's (implies --subagents).")
    ap.add_argument("--session-id", default=os.environ.get("CLAUDE_CODE_SESSION_ID"),
                    help="Session whose transcript to read (defaults to "
                         "$CLAUDE_CODE_SESSION_ID).")
    args = ap.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"provenance: file not found: {path}", file=sys.stderr)
        return 1

    rows = []
    if args.subagents or args.transcript:
        transcript = Path(args.transcript) if args.transcript else find_transcript(args.session_id)
        if transcript is None:
            # Not an error: audit mode, a resumed session, or a run with no
            # transcript on disk. The footer sentence still stamps.
            print("provenance: no session transcript found; "
                  "skipping the delegated-pass table.", file=sys.stderr)
        else:
            rows = collect_subagent_rows(transcript)
            if not rows:
                print("provenance: no delegated passes found in the transcript.",
                      file=sys.stderr)

    version = read_version(Path(args.skill_dir))
    stamp(path, args.model, args.skill, version, args.date, rows)
    detail = f" | {len(rows)} delegated pass(es)" if rows else ""
    print(f"Stamped provenance: {args.skill} v{version} | {args.model} | {args.date}{detail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
