#!/usr/bin/env python3
"""Stamp a provenance footer onto a generated report.

Shared across jet52 projects: jetmemo, jetredline, jetbriefcheck, jetrehearing.

The footer records, for later validation and comparison as the tools and the
Claude models change:
    Report generated by <model> using <skill> v<version> on <YYYY-MM-DD>.

Design: the parts that can be sourced deterministically *are* — the skill
version (from SKILL.md frontmatter `version:`, then a VERSION file) and the
date (the system clock). The model identifier is supplied by the caller (the
orchestrator, which alone knows the runtime model); this script never guesses
the model, because a model naming its own release is exactly the unreliable
self-report a validation record must not depend on.

With --subagents, the footer also carries a table of the delegated passes: the
model each subagent actually ran on and what it consumed. That comes from the
session transcript, not from the orchestrator's self-report — see
collect_subagent_rows() for the mechanism and its caveats.

Idempotent: re-running replaces an existing footer (table included) rather than
appending a duplicate, so it is safe to call on every regeneration.

Usage:
    python3 provenance.py --file REPORT.md --model "Claude Opus 4.8 (claude-opus-4-8)"
    python3 provenance.py --file REPORT.md --model "..." --subagents
    # optional: --date YYYY-MM-DD (defaults to today), --skill NAME, --skill-dir DIR

The skill name and version are derived from this script's own location
(<skill>/scripts/provenance.py), matching check_update.py, so the orchestrator
normally needs to pass only --file and --model.
"""

import argparse
import json
import os
import re
import sys
from datetime import date
from glob import glob
from pathlib import Path

# Per-skill constant (like check_update.py). The skill directory may be a
# symlink to a dev checkout whose folder is not named after the skill, so the
# name is hardcoded rather than derived from the path.
SKILL_NAME = "jetredline"

# Matches a previously stamped footer (with or without the leading rule, and
# with or without the delegated-pass table) at end of file, so re-stamping
# replaces rather than duplicates it. Anchored at end so that a report merely
# *quoting* a footer sentence mid-document is never truncated.
_FOOTER_RE = re.compile(
    r"\n*(?:---\s*\n+)?"
    r"\*Report generated by .+? using .+? on .+?\*"
    r"(?:\s*\n+\*\*Delegated passes\*\*\s*\n.*?)?"
    r"\s*$",
    re.S,
)

# --- delegated-pass usage ---------------------------------------------------
#
# Identifying which pass a subagent ran, in two tiers.
#
# Tier 1 (authoritative): since v4.8.0 every delegated pass is launched with a
# prompt that begins "Read <skill root>/references/pass-instructions/passN-*.md
# and follow it", so the instruction-file stem names the pass exactly.
#
# Tier 2 (fallback): older prompts inlined the instructions and opened with
# "You are running Pass 4 (fact-check) for a jetredline audit...", and a
# paraphrased prompt may do the same. A bare pass number is too generic to
# trust alone, so tier 2 also requires the prompt to name the skill.
#
# Either way the label comes from a fixed table -- no prompt text is ever
# carried into the report.
_PASS_FILE_RE = re.compile(r"pass-instructions/(pass\d+[a-z]?-[a-z0-9-]+)\.md", re.I)
_PASS_PROSE_RE = re.compile(r"\bPass\s+(\d+[AB]?)\b", re.I)
_PROSE_SCAN_CHARS = 400

PASS_LABELS = {
    "pass1-jurisdiction": "1 — Jurisdiction",
    "pass2-style": "2 — Style",
    "pass3b-citations": "3B — Citations",
    "pass4-factcheck": "4 — Fact check",
    "pass6-brief-matching": "6 — Brief matching",
    "pass7-dissent-crosscheck": "7 — Dissent cross-check",
}

PASS_NUMBER_LABELS = {
    "1": "1 — Jurisdiction",
    "2": "2 — Style",
    "3A": "3A — Citation format",
    "3B": "3B — Citations",
    "4": "4 — Fact check",
    "5": "5 — Analytical rigor",
    "6": "6 — Brief matching",
    "7": "7 — Dissent cross-check",
}


def identify_pass(prompt: str):
    """Label for the pass this prompt delegated, or None if it isn't one."""
    match = _PASS_FILE_RE.search(prompt)
    if match:
        return PASS_LABELS.get(match.group(1).lower())
    if "jetredline" not in prompt.lower():
        return None
    match = _PASS_PROSE_RE.search(prompt[:_PROSE_SCAN_CHARS])
    if match:
        return PASS_NUMBER_LABELS.get(match.group(1).upper())
    return None

_TABLE_HEADING = "**Delegated passes**"


def find_transcript(session_id: str):
    """Path to the session transcript, or None.

    Session IDs are UUIDs and unique across projects, so globbing every project
    directory beats reconstructing Claude Code's cwd-to-slug encoding.
    """
    if not session_id:
        return None
    matches = glob(
        os.path.expanduser(f"~/.claude/projects/*/{session_id}.jsonl")
    )
    return Path(matches[0]) if matches else None


def _human(n) -> str:
    """Compact token count: 2, 4.1k, 152.8k, 1.2M."""
    try:
        n = int(n)
    except (TypeError, ValueError):
        return "—"
    if n < 1000:
        return str(n)
    if n < 1_000_000:
        return f"{n / 1000:.1f}k"
    return f"{n / 1_000_000:.1f}M"


def _duration(ms) -> str:
    """Compact wall time: 48s, 3m 21s, 1h 04m."""
    try:
        secs = int(ms) // 1000
    except (TypeError, ValueError):
        return "—"
    if secs < 60:
        return f"{secs}s"
    if secs < 3600:
        return f"{secs // 60}m {secs % 60:02d}s"
    return f"{secs // 3600}h {(secs % 3600) // 60:02d}m"


def collect_subagent_rows(transcript_path) -> list:
    """Per-pass model and usage, read from the session transcript.

    Claude Code records a `toolUseResult` object for every completed Task call,
    carrying `resolvedModel`, `usage`, `totalToolUseCount`, and
    `totalDurationMs`. That is an internal format with no compatibility
    guarantee, so every field is treated as optional and any failure yields an
    empty list -- a missing table, never a failed run.

    Privacy: the prompt is read only to identify the pass against a fixed label
    table (see identify_pass). No prompt or result text is ever returned,
    because the stamped report goes into the case file.
    """
    rows = []
    try:
        with open(transcript_path, "r", encoding="utf-8") as fh:
            for line in fh:
                # Cheap prefilter -- transcripts run to hundreds of thousands
                # of lines and only a handful are Task results.
                if '"agentType"' not in line:
                    continue
                try:
                    record = json.loads(line)
                except ValueError:
                    continue
                result = record.get("toolUseResult")
                if not isinstance(result, dict) or "agentType" not in result:
                    continue

                prompt = result.get("prompt")
                if not isinstance(prompt, str):
                    continue
                label = identify_pass(prompt)
                if not label:
                    continue

                usage = result.get("usage")
                usage = usage if isinstance(usage, dict) else {}
                status = result.get("status")
                rows.append(
                    {
                        "pass": label,
                        "model": result.get("resolvedModel") or "unknown",
                        "input": usage.get("input_tokens"),
                        "output": usage.get("output_tokens"),
                        "cache_read": usage.get("cache_read_input_tokens"),
                        "tools": result.get("totalToolUseCount"),
                        "duration_ms": result.get("totalDurationMs"),
                        "status": status if status != "completed" else None,
                    }
                )
    except (OSError, ValueError):
        return []
    return rows


def subagent_table(rows: list) -> str:
    """Render the delegated-pass rows as a markdown table (empty string if none)."""
    if not rows:
        return ""
    lines = [
        _TABLE_HEADING,
        "",
        "| Pass | Model | In | Out | Cache read | Tools | Time |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        label = r["pass"]
        if r.get("status"):
            label += f" ({r['status']})"
        tools = r.get("tools")
        lines.append(
            "| {} | {} | {} | {} | {} | {} | {} |".format(
                label,
                r["model"],
                _human(r.get("input")),
                _human(r.get("output")),
                _human(r.get("cache_read")),
                tools if isinstance(tools, int) else "—",
                _duration(r.get("duration_ms")),
            )
        )
    return "\n".join(lines)


def find_skill_dir(script_path: Path) -> Path:
    """Locate the skill root (holding SKILL.md / VERSION) from this script's path.

    Works whether the script lives in <skill>/scripts/ (jetmemo, jetrehearing)
    or directly in <skill>/ (jetredline). Resolves symlinks first, so a skill
    mounted as a symlink to a dev checkout still resolves correctly.
    """
    here = script_path.resolve()
    for d in (here.parent, here.parent.parent, here.parent.parent.parent):
        if (d / "SKILL.md").exists() or (d / "VERSION").exists():
            return d
    return here.parent.parent


def read_version(skill_dir: Path) -> str:
    """Authoritative version: SKILL.md frontmatter `version:`, then VERSION file."""
    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        m = re.search(r"^version:\s*(.+?)\s*$", skill_md.read_text(), re.M)
        if m:
            return m.group(1).strip().strip("'\"")
    version_file = skill_dir / "VERSION"
    if version_file.exists():
        return version_file.read_text().strip()
    return "unknown"


def footer_line(model: str, skill: str, version: str, on_date: str) -> str:
    ver = f"v{version}" if version != "unknown" else "version unknown"
    return (
        f"*Report generated by {model} using {skill} {ver} on {on_date}. "
        f"AI-generated first draft for internal use; verify all citations and "
        f"findings before relying.*"
    )


def stamp(path: Path, model: str, skill: str, version: str, on_date: str,
          rows: list = None) -> None:
    text = path.read_text().rstrip()
    text = _FOOTER_RE.sub("", text).rstrip()
    footer = footer_line(model, skill, version, on_date)
    table = subagent_table(rows or [])
    if table:
        footer += "\n\n" + table
    path.write_text(text + "\n\n---\n\n" + footer + "\n")


def main() -> int:
    default_skill_dir = find_skill_dir(Path(__file__))

    ap = argparse.ArgumentParser(description="Stamp a provenance footer onto a report.")
    ap.add_argument("--file", required=True, help="Report file to stamp (markdown).")
    ap.add_argument("--model", required=True,
                    help='Runtime model identifier, e.g. "Claude Opus 4.8 (claude-opus-4-8)".')
    ap.add_argument("--skill", default=SKILL_NAME,
                    help="Skill name (defaults to this skill's SKILL_NAME constant).")
    ap.add_argument("--skill-dir", default=str(default_skill_dir),
                    help="Skill root holding SKILL.md / VERSION (defaults to this script's skill).")
    ap.add_argument("--date", default=date.today().isoformat(),
                    help="Generation date YYYY-MM-DD (defaults to today).")
    ap.add_argument("--subagents", action="store_true",
                    help="Append a table of the delegated passes (model and token "
                         "usage per pass), read from this session's transcript.")
    ap.add_argument("--transcript", default=None,
                    help="Transcript path to read instead of locating this "
                         "session's (implies --subagents).")
    ap.add_argument("--session-id", default=os.environ.get("CLAUDE_CODE_SESSION_ID"),
                    help="Session whose transcript to read (defaults to "
                         "$CLAUDE_CODE_SESSION_ID).")
    args = ap.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"provenance: file not found: {path}", file=sys.stderr)
        return 1

    rows = []
    if args.subagents or args.transcript:
        transcript = Path(args.transcript) if args.transcript else find_transcript(args.session_id)
        if transcript is None:
            # Not an error: audit mode, a resumed session, or a run with no
            # transcript on disk. The footer sentence still stamps.
            print("provenance: no session transcript found; "
                  "skipping the delegated-pass table.", file=sys.stderr)
        else:
            rows = collect_subagent_rows(transcript)
            if not rows:
                print("provenance: no delegated passes found in the transcript.",
                      file=sys.stderr)

    version = read_version(Path(args.skill_dir))
    stamp(path, args.model, args.skill, version, args.date, rows)
    detail = f" | {len(rows)} delegated pass(es)" if rows else ""
    print(f"Stamped provenance: {args.skill} v{version} | {args.model} | {args.date}{detail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
